baseURL = "https://plugins.zkga.me"
languageCode = "en-us"
title = "Dark Forest Plugins"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
staticDir = ["screenshots", "static", "javascript"]

[params]
  name = "Dark Forest Plugins"
  author = "Dark Forest Plugins"
  description = "A showcase of Dark Forest plugins from the community!"
  message = "Welcome to the Dark Forest Plugin showcase!"
  hideAutoMenu = false
  repo = "phated/df-plugins"
  branch = "showcase"

[[menu.main]]
  name = "Submit plugin"
  url = "https://github.com/phated/df-plugins##adding-your-plugin"

[social]
  twitter = "https://twitter.com/darkforest_eth"
